### ISSUE TITLE
https://postprocessing.tresjs.org/ is being referenced in README.md and doesn't work

### ISSUE THREAD

**Issue by shawn-mty** [Tresjs/post-processing#103]
**Describe the bug**
https://postprocessing.tresjs.org/ is being referenced in README.md and doesn't work (dead link)

**Comment by AntoninRousset** [comment]
It should be [https://post-processing.tresjs.org/](https://post-processing.tresjs.org/).

**Comment by Tinoooo** [comment]
Thank you for the report and the fix!
