### ISSUE TITLE
EffectComposer in Nuxt3 ,canvas is no color

### ISSUE THREAD

**Issue by oooowl** [Tresjs/post-processing#118]
**Describe the bug**
EffectComposer in Nuxt3 ,canvas is no color.

**Reproduction**
https://stackblitz.com/edit/github-fbtfij?file=app.vue

**Expected behavior**
![image](https://github.com/user-attachments/assets/9f84174e-f056-4653-bc1d-c10c69944e48)

**Screenshots**
![image](https://github.com/user-attachments/assets/244d5b48-1f82-4727-803c-825b61f27a3b)

**System Info**
nuxt:3.12.4

**Comment by Tinoooo** [comment]
I can't reproduce this. It was probably fixed with #123. Let me know if this occurs again for you.
