### ISSUE TITLE
Cannot read properties of undefined (reading 'canvas')

### ISSUE THREAD

**Issue by GustavoGomez092** [Tresjs/post-processing#49]
**Describe the bug**
A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!

Hi! Fist of all, What a great library! I'm playing with it, and so far... I LOVE IT! now... to the error, I am currently trying to use the post-processing package on a scene and I get the following error when I use it:

![image](https://github.com/Tresjs/post-processing/assets/45272016/44811685-62b7-409c-bbc8-9d1348e35449)

**Reproduction**
This same happens whenever you check the examples:
https://playground.tresjs.org/experiments/nuxt-stones

![image](https://github.com/Tresjs/post-processing/assets/45272016/7a3cb02f-738c-4afc-b63b-112c65adce9b)

**Steps**
1. Just adding the EffectComposer with a default bloom effect.

**Expected behavior**
For the effect composer component to work

**Screenshots**

**System Info**
Output of `npx envinfo --system --npmPackages '{vite,@tresjs/*, three, vue}' --binaries --browsers` 
```
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 323.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.5.2
  npmPackages:
    @tresjs/cientos: ^3.1.0 => 3.1.0 
    @tresjs/core: ^3.1.0 => 3.1.0 
    @tresjs/post-processing: ^0.3.0 => 0.3.0 
    vite: ^2.8.0 => 2.9.16 
```

**Additional context**

**Comment by Tinoooo** [comment]
I can't reproduce the bug. The playground example does not report any errors in the console. Let me know if I missed something.

**Comment by GustavoGomez092** [comment]
Got fixed with a version bump! Thank you for your time!
