### ISSUE TITLE
Postprocessing breaks on Nuxt

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/post-processing#58]
**Describe the bug**
Postprocessing Render seems to break on Nuxt.

**Reproduction**
https://stackblitz.com/edit/nuxt-starter-2qaqwx?file=nuxt.config.ts,components%2FTheExperience.vue,package.json,app.vue

**Steps**
1. Go to Reproduction
2. Resize

**Reproduction**
When resizing the clear color also goes blank. Effects don't work etc

**Expected behavior**
All smooth and working lol

**Screenshots**
![Screenshot 2023-09-27 at 13 26 13](https://github.com/Tresjs/post-processing/assets/4699008/09f550a1-1714-4612-a555-81579191ed95)

**System Info**
Output of `npx envinfo --system --npmPackages '{vite,@tresjs/*, three, vue}' --binaries --browsers` 

```
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    @tresjs/nuxt: ^1.1.7 => 1.1.7 
    @tresjs/post-processing: ^0.4.0 => 0.4.0 
```

**Additional context**

**Comment by JaimeTorrealba** [comment]
@Tinoooo I believe this is your :D

**Comment by alvarosabu** [comment]
Oh lol sorry @JaimeTorrealba hahaha

**Comment by alvarosabu** [comment]
@Tinoooo any chance to check on this? It's important to get post-processing demos working on the playground.
