### ISSUE TITLE
Improve bloom docs

### ISSUE THREAD

**Issue by Tinoooo** [Tresjs/post-processing#60]
**Is your feature request related to a problem? Please describe.**
The bloom effect seems like it is not working when used with the default parameters.

**Describe the solution you'd like**
The docs should convey how to use the bloom effect so it is visible in the scene.

**Comment by alvarosabu** [comment]
@Tinoooo agree, more than improve the docs, why don't we improve the DX and add some defaults so it's at least visible?

**Comment by Tinoooo** [comment]
> @Tinoooo agree, more than improve the docs, why don't we improve the DX and add some defaults so it's at least visible?
I'm not sure about this. One the one hand it adds DX on the other we stray away from the effect defaults.

**Comment by Tinoooo** [comment]
will be fixed in #123
