### ISSUE TITLE
Docs link broken in README

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/post-processing#72]
**Describe the bug**

The link to the docs is broken in [README.txt](https://github.com/Tresjs/post-processing/blob/main/README.md).

**Steps**

1. Go to https://github.com/Tresjs/post-processing/blob/main/README.md
2. Click on 'Checkout the [docs](https://postprocessing.tresjs.org/)' under the ["Docs" heading](https://github.com/Tresjs/post-processing/blob/main/README.md#docs).

**Expected behavior**

Link should work. 😊

**Comment by LeonardoRick** [comment]
Hey, yeah. I'm just discovering the Tres.js world, reached the page and it's not opening. How can I access the docs of this package? 
|:(|
|--|
|<img width="1439" alt="image" src="https://github.com/Tresjs/post-processing/assets/17517057/0826811a-64ef-471d-8e84-057d315ec0ea">|

**Comment by alvarosabu** [comment]
Is now live @andretchen0  https://post-processing.tresjs.org/
