### ISSUE TITLE
need help, How can we pass custom effect?

### ISSUE THREAD

**Issue by pilishen** [Tresjs/post-processing#86]
thanks for this great package, it's so elagant,  really appreciate

I'm having difficulty in passing custom shader effect into the `EffectComposer`, is it possible currently?

```
<Suspense>
       <EffectComposer ref="composer">
            <Bloom   />
       </EffectComposer>
</Suspense>
```
Suppose besides Bloom Effect, i still want to pass another shader effect, how could i achieve that?
```
import { ShaderPass } from 'postprocessing';
import Shader from './shader.js

<script setup>
    const shaderEffect = new ShaderPass(Shader)
    const composer  = ref()

   onMounted(()=>{
        if (composer.value) {
            composer.value.addPass(shaderEffect)
            composer.value.render()
          }
    })
</script>

```
That's my first attempt, but it didn't work, any help? thanks

**Comment by AntoninRousset** [comment]
To make it easy to add custom effects, could you export `useEffect` composable?
As in #105.

**Comment by Tinoooo** [comment]
`useEffect` is now exposed. So passing custom effects should work by creating an own component that uses the composable. The [Pixelation](https://github.com/Tresjs/post-processing/blob/main/src/core/effects/Pixelation.vue) component should be a good reference. @pilishen Let me know if this helps.
